In [2]:
import pandas as pd

df = pd.read_csv("/content/Student Performance Data.csv")

display(df.head())

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium
1,female,group C,some college,standard,69,90,88,247,completed,high
2,female,group B,master's degree,standard,90,95,93,278,none,high
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low
4,male,group C,some college,standard,76,78,75,229,none,high

In [4]:
SCORES = ["math score", "reading score", "writing score"]

add_average      = lambda df: df.assign(**{"average score": df[SCORES].mean(axis=1).round(2)})
high_achievers   = lambda df, threshold=240: df[df["total score"] >= threshold].reset_index(drop=True)
to_letter        = lambda avg: "A" if avg >= 90 else "B" if avg >= 80 else "C" if avg >= 70 else "D" if avg >= 60 else "F"
add_letter_grade = lambda df: add_average(df).assign(**{"letter grade": lambda d: d["average score"].apply(to_letter)})
summary_by       = lambda df, col: (df.groupby(col)[SCORES + ["total score"]].mean().round(2)
                                      .reset_index().sort_values("total score", ascending=False))
prep_comparison  = lambda df: summary_by(df, "test preparation course")

In [5]:
df_avg = add_average(df)
display(df_avg.head())

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect,average score
0,female,group B,bachelor's degree,standard,72,72,74,218,none,medium,72.67
1,female,group C,some college,standard,69,90,88,247,completed,high,82.33
2,female,group B,master's degree,standard,90,95,93,278,none,high,92.67
3,male,group A,associate's degree,free/reduced,47,57,44,148,none,low,49.33
4,male,group C,some college,standard,76,78,75,229,none,high,76.33

In [6]:
df_top = high_achievers(df)
print(len(df_top), "students scored 240+")
display(df_top.head())

198 students scored 240+

,gender,race/ethnicity,parental level of education,lunch,math score,reading score,writing score,total score,test preparation course,admission prospect
0,female,group C,some college,standard,69,90,88,247,completed,high
1,female,group B,master's degree,standard,90,95,93,278,none,high
2,female,group B,some college,standard,88,95,92,275,completed,high
3,male,group C,high school,standard,88,89,86,263,none,high
4,male,group E,some college,standard,97,87,82,266,none,high

In [7]:
df_grades = add_letter_grade(df)
display(df_grades[["average score", "letter grade"]].head(10))
display(df_grades["letter grade"].value_counts().sort_index())

   average score letter grade
0          72.67            C
1          82.33            B
2          92.67            A
3          49.33            F
4          76.33            C
5          77.33            C
6          91.67            A
7          40.67            F
8          65.00            D
9          49.33            F

letter grade
A     52
B    146
C    261
D    256
F    285
Name: count, dtype: int64

In [8]:
display(summary_by(df, "parental level of education"))

,parental level of education,math score,reading score,writing score,total score
3,master's degree,69.75,75.37,75.68,220.80
1,bachelor's degree,69.39,73.00,73.38,215.77
0,associate's degree,67.88,70.93,69.90,208.71
4,some college,67.13,69.46,68.84,205.43
5,some high school,63.50,66.94,64.89,195.32
2,high school,62.14,64.70,62.45,189.29

In [9]:
display(prep_comparison(df))

,test preparation course,math score,reading score,writing score,total score
0,completed,69.70,73.89,74.42,218.01
1,none,64.08,66.53,64.50,195.12

In [10]:
print(type(df_grades))
print(df.shape, df_grades.shape)

<class 'pandas.core.frame.DataFrame'>
(1000, 10) (1000, 12)